language: node_js
node_js:
  - "11.15.0"
script:
  - npm run build
install:
  - npm install
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project travis-firebase-demo --token $FIREBASE_TOKEN
